### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by durgesgameta** [lycaoduong/FcgFormer#1]
Dear authors multiple files are missing in the repo, no dataloader and the FcgFormer files.

**Comment by lycaoduong** [comment]
Thank you for your interest in my repository. All data and the FcgFormer model have been uploaded to HuggingFace. You can find the dataset and model using the following links or refer to the Readme file for more details:
Dataset: https://huggingface.co/datasets/lycaoduong/FTIR
FcgFormer model: https://huggingface.co/lycaoduong/FcgFormer

**Comment by lycaoduong** [comment]
The dataloader parts have now been committed as well. Please feel free to reach out if you have any questions!
