### ISSUE TITLE
 missing FcgFormer.py file

### ISSUE THREAD

**Issue by lalkrishna70135** [lycaoduong/FcgFormer#2]
we request you to provide the FcgFormer.py model we need it for research purposes. We are currently doing research in this field and we need to compare our model results with FcgFormer model. So we ask  you to upload the FcgFormer.py model and supporting files .

**Comment by lycaoduong** [comment]
The model is accessible on the Hugging Face model card for lycaoduong/FcgFormer. Please review the modeling_fcg.py file, as it includes the architecture of the FcgFormer model, which should be what you need.
